"""Per-game hints at the top of the system prompt: a table for known games, action-set templates for the rest.

    python3 game_hints.py apply  <bundle>/src/ARC3-Inference [--table hints.json] [--mode all|templates] [--dry-run]
    python3 game_hints.py derive <run_output_dir> [--out hints.json] [--merge hints.json]   # from OUR OWN runs
    python3 game_hints.py show   [--table hints.json]
    python3 game_hints.py --selftest

apply   writes inference/agent/game_hints.py (table + templates, no other dependency) and adds one guarded
        statement to ToolAgent.analyze(): on the first turn of a game the hint for that game is inserted
        after the first sentence of the system prompt. The game is identified from the runtime-state
        file name (<game_id>_p<i>_tool_runtime_state.json), the action set from valid_actions.
        Independent of the model (works with the fine-tune) and of the wm patches.
derive  builds table entries from our own transcripts: for every game that completed at least one
        level, the notes the agent itself held when the level ended (`goal:` and the first `rules:`
        of the last tool result before the completion) become that game's `mechanics`. Nothing is
        invented: a game we never progressed in gets no mechanics line.

READ THIS BEFORE USING THE TABLE
  * The shipped table has NO mechanics text. It holds only what the repo documents: the unofficial
    nicknames from the forum list (11 games), the action tags from the environment metadata, and the six
    games where ACTION7 is a real mechanic (verified on our transcripts). The public game sources are
    obfuscated and only 12 games have even a level-1 solution on file, so real mechanics have to come
    from `derive` on a notes/wm run -- that is why the subcommand exists.
  * Table hints only fire on the 25 PUBLIC game ids. A run that uses them is no longer a measurement
    of the agent on unseen games: its public-25 mean must not be compared with earlier runs or used to
    predict the LB. Use --mode templates for any run whose public score is meant as evidence.
  * Hidden games get the template for their action set (click-only / keys-only / keys+click / ACTION7).
    Those templates are generic advice written from the autopsy (no-ops, starved turns), not knowledge
    of any hidden game. Whether they help is an A/B question, not a given.
"""
import argparse
import glob
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
MARK = "game_hints import hint_for"
ANALYZE_ANCHOR = "        self._current_valid_actions = _normalize_valid_actions(valid_actions)\n"
ANALYZE_ADD = ('        if not getattr(self, "_game_hint_done", False):\n'
               '            self._game_hint_done = True\n'
               '            try:\n'
               '                from .game_hints import hint_for, insert_hint\n'
               '                self._system_prompt = insert_hint(\n'
               '                    self._system_prompt, hint_for(state_path.name, self._current_valid_actions))\n'
               '            except Exception:  # a hint must never cost a game\n'
               '                pass\n')

# unofficial nicknames: forum list quoted in CLOUD_MIGRATION.md (2026-09-24); tags: environment_files/*/metadata.json;
# action7: games whose valid_actions offer ACTION7 as a mechanic (CLOUD_MIGRATION.md 2026-09-24 late3)
NICK = {"bp35": "buoyancy puzzle", "cn04": "connector network", "tu93": "traverse unharmed", "tn36": "toggle navigation",
        "sb26": "sequence builder", "wa30": "warehouse agents", "ls20": "lock smith", "vc33": "volume control",
        "lp85": "loop placement", "sk48": "sliding kebab", "ar25": "axis reflections"}
TAGS = {"ar25": "keyboard_click", "bp35": "keyboard_click", "cd82": "keyboard_click", "cn04": "keyboard_click",
        "dc22": "keyboard_click", "ft09": "", "g50t": "keyboard", "ka59": "keyboard_click", "lf52": "click", "lp85": "click",
        "ls20": "keyboard", "m0r0": "keyboard_click", "r11l": "click", "re86": "keyboard_click", "s5i5": "click",
        "sb26": "keyboard_click", "sc25": "keyboard_click", "sk48": "keyboard_click", "sp80": "keyboard_click",
        "su15": "click", "tn36": "click", "tr87": "keyboard", "tu93": "keyboard_click", "vc33": "click", "wa30": "keyboard"}
ACTION7 = ("ar25", "bp35", "lf52", "sb26", "sk48", "su15")


def default_table():
    t = {}
    for g in sorted(TAGS):
        e = {}
        if g in NICK:
            e["nickname"] = NICK[g]
        if g in ACTION7:
            e["action7"] = True
        t[g] = e
    return t


RUNTIME = r'''"""Game hints for the system prompt. Generated by dev/game_hints.py -- edit the table there."""
MODE = %(mode)r          # all | templates | off
TABLE = %(table)s

TEMPLATES = {
    "click": ("Only clicks act here; nothing moves by itself. First call: click one cell of every distinct "
              "object kind once (not empty background) and read what changed; then act on the kind that responds."),
    "keys": ("Only keys act here. First call: press each key once and find which object moves and what blocks it; "
             "a key that changes only a few cells is a no-op or is spending a move counter."),
    "both": ("Keys and clicks both act. In the first call press each key once and click one cell of every distinct "
             "object kind once, then read which of them changed the board before planning anything."),
    "action7": ("ACTION7 is offered: it is a mechanic of this game, not necessarily undo (in one known game it "
                "rotates the piece). Try it once early and see what it changes."),
}


def game_of(name):
    """'<game>-<hash>_p0_tool_runtime_state.json' -> '<game>'."""
    base = str(name).split("/")[-1]
    return base.split("-")[0].split("_")[0].lower()


def hint_for(state_name, valid_actions):
    if MODE == "off":
        return ""
    acts = {str(a).upper() for a in valid_actions or []}
    keys = bool(acts & {"UP", "DOWN", "LEFT", "RIGHT", "SPACE"})
    click = "MOUSE" in acts
    parts = []
    entry = TABLE.get(game_of(state_name)) if MODE == "all" else None
    if entry:
        if entry.get("mechanics"):
            parts.append("Known from earlier play of this game (verify, then use): " + entry["mechanics"])
        if entry.get("nickname"):
            parts.append("Players call this game '%%s' -- a clue about its theme, not a rule." %% entry["nickname"])
    if "ACTION7" in acts:
        parts.append(TEMPLATES["action7"])
    if not (entry and entry.get("mechanics")):
        kind = "both" if keys and click else "click" if click else "keys" if keys else None
        if kind:
            parts.append(TEMPLATES[kind])
    return "GAME NOTES: " + " ".join(parts) if parts else ""


def insert_hint(system_prompt, hint):
    """After the first sentence of the system prompt; once."""
    if not hint or "GAME NOTES: " in system_prompt:
        return system_prompt
    head = "You are a coding agent solving a grid-based puzzle game."
    if system_prompt.startswith(head):
        return head + "\n\n" + hint + "\n" + system_prompt[len(head):]
    return hint + "\n\n" + system_prompt
'''


def runtime_source(table, mode="all"):
    assert mode in ("all", "templates", "off")
    import pprint
    src = RUNTIME % dict(mode=mode, table=pprint.pformat(json.loads(json.dumps(table)), sort_dicts=True, width=110))
    compile(src, "game_hints.py", "exec")
    return src


def patch_tool_agent(text):
    if MARK in text:
        return text
    n = text.count(ANALYZE_ANCHOR)
    if n != 1:
        raise SystemExit(f"tool_agent.py: anchor matched {n} times (need exactly 1): {ANALYZE_ANCHOR.strip()!r}")
    if "state_path: Path," not in text or "self._system_prompt = _build_system_prompt(" not in text:
        raise SystemExit("tool_agent.py: analyze(state_path, ...) / self._system_prompt not found")
    out = text.replace(ANALYZE_ANCHOR, ANALYZE_ANCHOR + ANALYZE_ADD)
    compile(out, "tool_agent.py", "exec")
    return out


def apply(root, table=None, mode="all", dry_run=False):
    agent = os.path.join(root, "inference", "agent")
    ta_path, rt_path = os.path.join(agent, "tool_agent.py"), os.path.join(agent, "game_hints.py")
    text = open(ta_path).read()
    new_ta = patch_tool_agent(text)
    new_rt = runtime_source(table if table is not None else default_table(), mode)
    old_rt = open(rt_path).read() if os.path.exists(rt_path) else None
    if new_ta == text and new_rt == old_rt:
        return "already patched"
    if dry_run:
        return "dry run ok: anchor unique, both files compile"
    open(ta_path, "w").write(new_ta)
    open(rt_path, "w").write(new_rt)
    return "patched (mode %s, %d table games, %d with mechanics)" % (
        mode, len(table or default_table()), sum(1 for e in (table or default_table()).values() if e.get("mechanics")))


# ----------------------------------------------------------------------------------------------- derive
RE_MARK = re.compile(r"^\[([A-Z][^\]\n]*)\]\s*$", re.M)
RE_GOAL = re.compile(r"^[ \t]*['\"]?goal['\"]?[ \t]*:[ \t]*(\S.*?)[ \t]*$", re.M)
RE_RULES = re.compile(r"^([ \t]*)['\"]?rules?['\"]?[ \t]*:[ \t]*(.*)$", re.M)


def _tool_results(transcript):
    marks = list(RE_MARK.finditer(transcript))
    return [transcript[m.end():marks[i + 1].start() if i + 1 < len(marks) else len(transcript)]
            for i, m in enumerate(marks) if m.group(1).strip().upper().startswith("TOOL RESULT")]


def _clean(s, limit):
    s = re.sub(r"\s+", " ", s.strip().strip("'\",[]{}")).strip()
    words = s.split()
    return " ".join(words[:limit]) + ("..." if len(words) > limit else "")


def notes_of(text):
    """(goal, [rules]) from one rendered tool result holding the agent's notes; ('', []) if none."""
    g = RE_GOAL.findall(text)
    goal = _clean(g[-1], 30) if g else ""
    rules = []
    for m in RE_RULES.finditer(text):
        indent, inline = len(m.group(1)), m.group(2).strip()
        got = []
        if inline and inline not in ("|", "{}", "[]"):
            got.append(inline)
        for line in text[m.end():].split("\n")[1:]:
            if not line.strip():
                continue
            if len(line) - len(line.lstrip()) <= indent:
                break
            item = line.strip().lstrip("-").strip()
            if item:
                got.append(item)
        if got:
            rules = got
    return goal, [_clean(r, 25) for r in rules if len(r.split()) >= 3][:2]


def derive(run_dir, min_levels=1):
    """-> {game: {'mechanics': ..., 'levels': n, 'source': path}} from *_events.jsonl of one of our runs."""
    out = {}
    for ep in sorted(glob.glob(os.path.join(run_dir, "**", "*_events.jsonl"), recursive=True)):
        game = os.path.basename(ep).split("-")[0].split("_")[0].lower()
        last_notes, at_completion, score, pending = ("", []), None, 0, False
        for line in open(ep, encoding="utf-8", errors="replace"):
            try:
                e = json.loads(line)
            except ValueError:
                continue
            if e.get("type") == "action" and isinstance(e.get("score"), int) and e["score"] > score:
                score, pending = e["score"], True
                if last_notes[0]:
                    at_completion = last_notes                     # what the agent believed when the level fell
            elif e.get("type") == "analysis":
                for res in _tool_results(e.get("transcript") or ""):
                    n = notes_of(res)
                    if n[0]:
                        last_notes = n
                if pending and at_completion is None and last_notes[0]:
                    at_completion = last_notes                     # notes written in the same turn as the completion
                pending = False
        if score >= min_levels and at_completion and at_completion[0]:
            goal, rules = at_completion
            text = "goal: " + goal + ("; " + "; ".join(rules) if rules else "")
            out[game] = {"mechanics": text, "levels": score, "source": os.path.relpath(ep, run_dir)}
    return out


def merge(table, derived):
    """Add derived mechanics to a table; an entry from a run that got further replaces an older one."""
    t = json.loads(json.dumps(table))
    for g, d in derived.items():
        e = t.setdefault(g, {})
        if not e.get("mechanics") or d["levels"] > e.get("levels", 0):
            e.update(mechanics=d["mechanics"], levels=d["levels"], source=d["source"])
    return t


# --------------------------------------------------------------------------------------------- selftest
def selftest():
    import shutil
    import tempfile
    import types
    repo = os.path.dirname(os.path.dirname(HERE))
    # the shipped table is exactly the documented facts, and matches the environment metadata on disk
    t = default_table()
    assert len(t) == 25 and sum("nickname" in e for e in t.values()) == 11 and sum(e.get("action7", False) for e in t.values()) == 6
    assert not any("mechanics" in e for e in t.values())
    metas = glob.glob(os.path.join(repo, "arc-agi-3", "environment_files", "*", "*", "metadata.json"))
    for mp in metas:
        m = json.load(open(mp))
        assert TAGS[m["game_id"].split("-")[0]] == (m.get("tags") or [""])[0], m["game_id"]
    assert len(metas) in (0, 25)
    ns = {}
    exec(runtime_source(t, "all"), ns)
    hint, ins = ns["hint_for"], ns["insert_hint"]
    kc, k, c = ["UP", "DOWN", "LEFT", "RIGHT", "SPACE", "MOUSE", "RESET"], ["UP", "DOWN", "LEFT", "RIGHT", "RESET"], ["MOUSE", "RESET"]
    h = hint("ls20-9607627b_p0_tool_runtime_state.json", k)
    assert h.startswith("GAME NOTES: ") and "'lock smith'" in h and "Only keys act" in h and "ACTION7" not in h
    h = hint("ar25-0c556536_p0_tool_runtime_state.json", kc + ["ACTION7"])
    assert "'axis reflections'" in h and "ACTION7 is offered" in h and "Keys and clicks both act" in h
    h = hint("zz99-deadbeef_p0_tool_runtime_state.json", c)                      # a hidden game: template only
    assert h == "GAME NOTES: " + ns["TEMPLATES"]["click"]
    assert hint("zz99-deadbeef_p3_tool_runtime_state.json", ["RESET"]) == ""
    # a derived mechanics line replaces the generic template and is labelled as to-be-verified
    t2 = merge(t, {"ls20": {"mechanics": "goal: bring the key to the lock; arrows move the key", "levels": 2, "source": "x"}})
    exec(runtime_source(t2, "all"), ns)
    h = ns["hint_for"]("ls20-9607627b_p0_tool_runtime_state.json", k)
    assert "Known from earlier play of this game (verify, then use): goal: bring the key to the lock" in h and "Only keys act" not in h
    exec(runtime_source(t2, "templates"), ns)                                    # measurement mode: no table
    h = ns["hint_for"]("ls20-9607627b_p0_tool_runtime_state.json", k)
    assert "lock smith" not in h and "bring the key" not in h and h == "GAME NOTES: " + ns["TEMPLATES"]["keys"]
    exec(runtime_source(t2, "off"), ns)
    assert ns["hint_for"]("ls20-9607627b_p0_tool_runtime_state.json", k) == ""
    sp = "You are a coding agent solving a grid-based puzzle game.\nREST"
    out = ins(sp, "GAME NOTES: x")
    assert out == "You are a coding agent solving a grid-based puzzle game.\n\nGAME NOTES: x\n\nREST" and ins(out, "GAME NOTES: y") == out
    assert ins(sp, "") == sp and ins("Other prompt", "GAME NOTES: x").startswith("GAME NOTES: x\n\nOther")

    with tempfile.TemporaryDirectory() as tmp:
        # apply on a copy of the real agent directory; the inserted statement runs against a stand-in agent
        root = os.path.join(repo, "bundle_fast", "src", "ARC3-Inference")
        dst = os.path.join(tmp, "ARC3-Inference")
        os.makedirs(os.path.join(dst, "inference"))
        shutil.copytree(os.path.join(root, "inference", "agent"), os.path.join(dst, "inference", "agent"))
        before = open(os.path.join(dst, "inference", "agent", "tool_agent.py")).read()
        assert apply(dst, dry_run=True).startswith("dry run ok")
        assert apply(dst).startswith("patched (mode all, 25 table games, 0 with mechanics)") and apply(dst) == "already patched"
        after = open(os.path.join(dst, "inference", "agent", "tool_agent.py")).read()
        assert after.replace(ANALYZE_ADD, "") == before and after.count(ANALYZE_ADD) == 1
        assert apply(dst, t2, "templates").startswith("patched (mode templates")       # table or mode change rewrites the module only
        assert open(os.path.join(dst, "inference", "agent", "tool_agent.py")).read() == after
        apply(dst, t2, "all")
        pkg = types.ModuleType("gh_pkg")
        pkg.__path__ = [os.path.join(dst, "inference", "agent")]
        sys.modules["gh_pkg"] = pkg
        body = "def run(self, state_path, valid_actions):\n" + ANALYZE_ANCHOR.replace("_normalize_valid_actions(valid_actions)", "valid_actions") + ANALYZE_ADD
        g = {"__package__": "gh_pkg", "__name__": "gh_pkg.tool_agent"}
        exec(body, g)
        from pathlib import Path
        agent = types.SimpleNamespace(_system_prompt=sp)
        g["run"](agent, Path("/x/artifacts/ls20-9607627b_p0_tool_runtime_state.json"), k)
        assert "bring the key to the lock" in agent._system_prompt and agent._game_hint_done
        first = agent._system_prompt
        g["run"](agent, Path("/x/artifacts/ls20-9607627b_p0_tool_runtime_state.json"), k)      # later turns: unchanged
        assert agent._system_prompt == first
        os.remove(os.path.join(dst, "inference", "agent", "game_hints.py"))                  # a missing module costs nothing
        agent2 = types.SimpleNamespace(_system_prompt=sp)
        for m in [m for m in sys.modules if m.startswith("gh_pkg.")]:
            del sys.modules[m]
        g["run"](agent2, Path("/x/artifacts/ls20-9607627b_p0_tool_runtime_state.json"), k)
        assert agent2._system_prompt == sp

        # derive: notes as the harness renders them; only games that completed a level yield a line
        def tool(body):
            return "[SYSTEM PROMPT]\ngoal: this is prompt text, not notes\n\n[TOOL RESULT: python]\n%s\n\n" % body
        art = os.path.join(tmp, "run", "artifacts")
        os.makedirs(art)

        def write(game, events):
            with open(os.path.join(art, "%s-abcd1234_p0_events.jsonl" % game), "w") as f:
                for e in events:
                    f.write(json.dumps(e) + "\n")
        notes1 = "notes:\n  goal: push the yellow box onto the green cell\n  rules:\n    - arrows move the blue player one cell\n    - the box moves when pushed\n    - walls block\n  plan: go right\nwm: {}"
        notes2 = "goal: reach the exit before the counter runs out\nrules: stepping on red resets the level\nuncertain: []"
        write("ft09", [{"type": "initial", "score": 0},
                       {"type": "analysis", "analysis_step": 1, "transcript": tool("goal: unknown yet\nrules: []")},
                       {"type": "analysis", "analysis_step": 2, "transcript": tool(notes1)},
                       {"type": "action", "score": 1, "analysis_step": 3},
                       {"type": "analysis", "analysis_step": 3, "transcript": tool("goal: level 2 looks different")}])
        write("tu93", [{"type": "initial", "score": 0}, {"type": "action", "score": 1, "analysis_step": 1},
                       {"type": "analysis", "analysis_step": 1, "transcript": tool(notes2)}])
        write("bp35", [{"type": "initial", "score": 0}, {"type": "analysis", "analysis_step": 1, "transcript": tool(notes1)},
                       {"type": "action", "score": 0, "analysis_step": 2}])
        d = derive(os.path.join(tmp, "run"))
        assert set(d) == {"ft09", "tu93"}, d
        assert d["ft09"]["mechanics"] == ("goal: push the yellow box onto the green cell; arrows move the blue player one cell; "
                                         "the box moves when pushed") and d["ft09"]["levels"] == 1
        assert d["tu93"]["mechanics"] == "goal: reach the exit before the counter runs out; stepping on red resets the level"
        assert "prompt text" not in json.dumps(d)
        m = merge(t, d)
        assert m["ft09"]["mechanics"] and "mechanics" not in m["bp35"] and m["tu93"]["nickname"] == "traverse unharmed"
        better = merge(m, {"ft09": {"mechanics": "goal: B", "levels": 3, "source": "y"}, "tu93": {"mechanics": "goal: C", "levels": 1, "source": "y"}})
        assert better["ft09"]["mechanics"] == "goal: B" and better["tu93"]["mechanics"] == m["tu93"]["mechanics"]
    print("selftest ok: shipped table = 25 public games, 11 nicknames, 6 ACTION7 flags, no mechanics text, tags equal "
          "the environment metadata; known game -> table hint, unknown game -> action-set template, mode templates/off "
          "drop the table; the statement added to analyze() inserts the hint once after the first prompt sentence and "
          "is a no-op if the module is missing; derive takes goal + two rules from the notes held when a level was "
          "completed and ignores games that never completed one")


if __name__ == "__main__":
    if len(sys.argv) >= 2 and sys.argv[1] == "--selftest":
        selftest()
        sys.exit(0)
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)
    a1 = sub.add_parser("apply")
    a1.add_argument("root")
    a1.add_argument("--table")
    a1.add_argument("--mode", choices=["all", "templates", "off"], default="all")
    a1.add_argument("--dry-run", action="store_true")
    a2 = sub.add_parser("derive")
    a2.add_argument("run_dir")
    a2.add_argument("--out", default="game_hints_table.json")
    a2.add_argument("--merge")
    a2.add_argument("--min-levels", type=int, default=1)
    a3 = sub.add_parser("show")
    a3.add_argument("--table")
    a = ap.parse_args()
    if a.cmd == "apply":
        print(apply(a.root, json.load(open(a.table)) if a.table else None, a.mode, a.dry_run))
    elif a.cmd == "derive":
        d = derive(a.run_dir, a.min_levels)
        base = json.load(open(a.merge)) if a.merge else default_table()
        json.dump(merge(base, d), open(a.out, "w"), indent=1, sort_keys=True)
        for g, e in sorted(d.items()):
            print("%s (lv %d): %s" % (g, e["levels"], e["mechanics"]))
        print("%d game(s) with mechanics from this run -> %s (READ every line before applying)" % (len(d), a.out))
    else:
        t = json.load(open(a.table)) if a.table else default_table()
        ns = {}
        exec(runtime_source(t, "all"), ns)
        for g in sorted(t):
            acts = (["UP", "DOWN", "LEFT", "RIGHT"] if "keyboard" in TAGS.get(g, "") else []) + (["MOUSE"] if "click" in TAGS.get(g, "") else [])
            print(g, "|", ns["hint_for"](g + "-x_p0_tool_runtime_state.json", acts + (["ACTION7"] if t[g].get("action7") else [])))
